"""Fix upgraded_at default value

Revision ID: 42680eb1a56d
Revises: 0d097f6e8fef
Create Date: 2025-10-20 21:00:11.157901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42680eb1a56d'
down_revision: Union[str, None] = '0d097f6e8fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
