"""Add siret to suppliers

Revision ID: ccab67ca40be
Revises: fa018cfd3cd1
Create Date: 2025-10-20 19:50:17.251881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccab67ca40be'
down_revision: Union[str, None] = 'fa018cfd3cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('siret', sa.String(length=14), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'siret')
    # ### end Alembic commands ###
